# Generated by Django 5.2.17 on 2026-09-18 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DifficultyXPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20, unique=True)),
                ('xp_reward', models.PositiveIntegerField(help_text='XP awarded for solving a problem of this difficulty')),
            ],
            options={
                'verbose_name': 'Difficulty XP Configuration',
                'verbose_name_plural': 'Difficulty XP Configurations',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Full markdown problem description')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=20)),
                ('challenge_level', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Progression tier from 1 (Beginner) to 5 (Expert)')),
                ('xp_reward', models.PositiveIntegerField(default=50, help_text='XP awarded on first accepted solve')),
                ('constraints', models.TextField(blank=True, help_text='Constraints on inputs and bounds')),
                ('input_format', models.TextField(blank=True, help_text='Input stream format specification')),
                ('output_format', models.TextField(blank=True, help_text='Expected output format specification')),
                ('examples', models.JSONField(blank=True, default=list, help_text='List of example inputs, outputs, and explanations')),
                ('starter_code', models.TextField(blank=True, help_text='Initial C++ boilerplate provided to the user')),
                ('language', models.CharField(default='cpp', help_text='Target programming language', max_length=50)),
                ('time_limit_seconds', models.FloatField(default=2.0, help_text='Maximum CPU time limit in seconds')),
                ('memory_limit_kb', models.PositiveIntegerField(default=262144, help_text='Memory limit in KB (256 MB)')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='problems.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tag')),
            ],
            options={
                'ordering': ['challenge_level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_data', models.TextField(help_text='Standard input provided to the program')),
                ('expected_output', models.TextField(help_text='Exact standard output expected')),
                ('is_sample', models.BooleanField(default=False, help_text='If true, visible on the problem page as an example')),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty', 'is_published'], name='problems_pr_difficu_283da2_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['challenge_level', 'is_published'], name='problems_pr_challen_0b712a_idx'),
        ),
    ]
