# Generated by Django 5.2.17 on 2026-09-19 05:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++')], db_index=True, default='python', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=20)),
                ('challenge_level', models.PositiveSmallIntegerField(default=2, help_text='Skill level tier (1-5)')),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField(help_text='Detailed markdown project brief, architecture overview, and goals')),
                ('technologies', models.JSONField(blank=True, default=list, help_text="List of tech tags (e.g. ['Node.js', 'EventLoop'])")),
                ('starter_files', models.JSONField(blank=True, default=dict, help_text='Dictionary of filename to initial boilerplate')),
                ('xp_reward', models.PositiveIntegerField(default=150, help_text='Bonus XP awarded upon project completion')),
                ('estimated_minutes', models.PositiveIntegerField(default=60, help_text='Estimated time to complete')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Guided Project',
                'verbose_name_plural': 'Guided Projects',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Step order within the project (1, 2, 3...)')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Markdown step requirements and architectural specifications')),
                ('starter_code', models.TextField(blank=True, help_text='Code skeleton for this milestone')),
                ('test_harness_code', models.TextField(help_text='Verification test runner code executed in the sandbox')),
                ('hints', models.JSONField(blank=True, default=list, help_text='List of progressive guidance hints')),
                ('xp_reward', models.PositiveIntegerField(default=50, help_text='XP awarded when this milestone passes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='IN_PROGRESS', max_length=30)),
                ('current_milestone_order', models.PositiveIntegerField(default=1)),
                ('completed_milestones', models.JSONField(blank=True, default=list, help_text='List of completed milestone IDs')),
                ('submitted_code', models.JSONField(blank=True, default=dict, help_text='Mapping of milestone_id to code string')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Project Progress',
                'verbose_name_plural': 'User Project Progress Records',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
