# Generated by Django 5.2.17 on 2026-09-18 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('xp_threshold', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(default='Coder', max_length=64)),
            ],
            options={
                'verbose_name': 'Level Requirement',
                'verbose_name_plural': 'Level Requirements',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('SOLVE', 'Solved Problem'), ('LEVEL_UP', 'Level Up'), ('SUBMISSION', 'Submission')], default='SOLVE', max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='progress_ac_user_id_fd6d22_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('first_solved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submission')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress Records',
                'indexes': [models.Index(fields=['user', 'solved'], name='progress_us_user_id_73a28d_idx'), models.Index(fields=['problem', 'solved'], name='progress_us_problem_aa4144_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'problem'), name='unique_user_problem_progress')],
            },
        ),
    ]
