export const ENDPOINTS = {
  ADMIN: {
    ANALYTICS: '/admin/analytics/',
    PROBLEMS: '/admin/problems/',
    PROJECTS: '/admin/projects/',
    USERS: '/admin/users/',
    SUBMISSIONS: '/admin/submissions/',
  },
  AUTH: {
    CSRF: '/auth/csrf/',
    REGISTER: '/auth/register/',
    LOGIN: '/auth/login/',
    LOGOUT: '/auth/logout/',
    REFRESH: '/auth/token/refresh/',
    ME: '/auth/me/',
    CHANGE_PASSWORD: '/auth/change-password/',
    VERIFY_OTP: '/auth/verify-otp/',
    RESEND_OTP: '/auth/resend-otp/',
    REQUEST_EMAIL_CHANGE: '/auth/request-email-change/',
    CONFIRM_EMAIL_CHANGE: '/auth/confirm-email-change/',
  },
  PROBLEMS: '/problems/',
  SUBMISSIONS: '/submissions/',
  DASHBOARD: '/dashboard/',
  LEADERBOARD: '/leaderboard/',
  ACHIEVEMENTS: '/achievements/',
  PROJECTS: '/projects/',
  PORTFOLIO: '/portfolio/',
  PROGRESS: '/progress/',
  CATEGORIES: '/categories/',
  TAGS: '/tags/',
};
