# Generated by Django 5.2.17 on 2026-10-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationotp_new_email_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-total_xp', '-problems_solved_count', 'id'], name='idx_profile_xp_rank'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-problems_solved_count', '-total_xp', 'id'], name='idx_profile_solved_rank'),
        ),
    ]
