# Generated by Django 5.2.17 on 2026-10-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_idx_profile_xp_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationotp',
            name='otp_code',
            field=models.CharField(max_length=128),
        ),
    ]
