# Generated by Django 5.2.17 on 2026-09-18 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='cpp', max_length=50)),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('COMPILATION_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('INTERNAL_ERROR', 'Internal Error')], db_index=True, default='PENDING', max_length=30)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds (max across test cases)', null=True)),
                ('memory_usage', models.PositiveIntegerField(blank=True, help_text='Memory usage in KB (max across test cases)', null=True)),
                ('compile_output', models.TextField(blank=True, help_text='Compiler stderr or diagnostic output')),
                ('error_message', models.TextField(blank=True, help_text='System error or evaluation failure message')),
                ('passed_test_cases_count', models.PositiveIntegerField(default=0)),
                ('total_test_cases_count', models.PositiveIntegerField(default=0)),
                ('is_sample_run', models.BooleanField(db_index=True, default=False, help_text='True if run only against public sample test cases')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('COMPILATION_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('INTERNAL_ERROR', 'Internal Error')], max_length=30)),
                ('execution_time', models.FloatField(blank=True, help_text='Runtime in seconds', null=True)),
                ('memory_usage', models.PositiveIntegerField(blank=True, help_text='Memory in KB', null=True)),
                ('actual_output', models.TextField(blank=True, help_text='Captured standard output')),
                ('stderr_output', models.TextField(blank=True, help_text='Captured standard error')),
                ('order', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_results', to='problems.testcase')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-created_at'], name='submissions_user_id_7cc934_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', '-created_at'], name='submissions_problem_35c851_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-created_at'], name='submissions_status_fa968c_idx'),
        ),
    ]
